"""
Multi-format export pipeline for generated CAD geometry.

cad_generator.py previously hardcoded exactly two output formats (STEP
via cq.exporters, STL via cq.exporters). This module generalizes that
into a real Tier-1 export matrix:

    step  - exact B-Rep solid, mechanical CAD interchange (SolidWorks,
            Fusion 360, CATIA), CNC milling/turning, injection molding.
            Uses cq.exporters (STEPControl_Writer under the hood).
    stl   - triangulated mesh, additive manufacturing (FDM/SLA/SLS) and
            the in-browser three.js preview. Uses cq.exporters.
    iges  - exact B-Rep solid, legacy mechanical interchange. cadquery's
            own exporters module (2.3.1) doesn't expose an IGES
            ExportType - only STEPControl_Writer is wired up - so this
            calls OCP's IGESControl_Writer directly. That's not a new
            dependency: OCP is the OCCT binding cadquery is already
            built on, so this uses the same kernel STEP export uses.
    dxf   - true multi-view orthographic drawing (front/top/side), each
            view built via OCCT's HLR (hidden-line-removal) algorithm,
            for laser/plasma/waterjet cutting and full technical
            drawings - not a placeholder, not a single cross-section.
    pdf   - 1:1 scale vector engineering drawing with the same
            front/top/side views, a title block, and per-view labels,
            for shop-floor printing and dimensional inspection.

Scope notes (read before assuming more than what's here):

  * DXF/PDF are a real multi-view orthographic projection: front, top,
    and right-side views, each generated via OCCT's HLRBRep_Algo hidden-
    line-removal algorithm (through OCP, the same OCCT binding cadquery
    itself is built on - no new dependency), which separates each view's
    edges into visible (solid line) and hidden (dashed line) sets. This
    replaced the old single-horizontal-section approach (`Workplane.
    section()` at Z=0), which only captured geometry that happened to
    intersect one cutting plane - a stepped shaft's diameter change
    along its axis, for example, was invisible to it. There is no
    `multi_view`/`view_mode` flag; this is simply what `export_dxf` and
    `export_pdf` do now, for every part.
  * Assemblies get a *multi-part* drawing on top of that: `export_all`
    accepts a `parts` list (see assembly.get_assembly_parts) and, when
    given one, lays out one full front/top/side block per sub-part
    (each individually labeled) instead of a single block for the
    merged compound. This is a separate axis from multi-view - a
    single-part export always uses multi-view; a multi-part export uses
    multi-view *per part*, stacked on one sheet.
  * DXF layers are VISIBLE / HIDDEN / LABELS / BORDER, one drawing-line
    classification that applies to any part geometry, replacing the old
    PIECE_OUTLINE / HOLES / CENTERLINES set derived from section-wire
    nesting (which doesn't generalize to HLR edges - HLR doesn't produce
    closed hole wires, it produces visible/hidden edge segments).
  * GLTF is intentionally not included in this delivery. cadquery 2.3.1
    doesn't support it natively and a correct implementation needs an
    extra mesh-conversion dependency (e.g. trimesh) that wasn't in
    scope to add, test, and pin without being able to verify the
    resulting glTF against a viewer in this environment. Flagging this
    explicitly rather than shipping an unverified stub.
  * This module was written and reviewed against the cadquery 2.3.1 /
    OCP API surface pinned in requirements.txt, but could not be
    executed against real OCCT geometry in the sandbox this was
    authored in (no network access to install cadquery's native
    dependencies). Run `pytest tests/test_exporters.py` in an
    environment with the project's actual dependencies installed
    (the existing Dockerfile/CI already has them) before shipping.
"""
from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass
from pathlib import Path
from typing import Union

import cadquery as cq

from exceptions import GenerationError, UnsupportedFormatError
from logging_config import get_logger

logger = get_logger(__name__)

SUPPORTED_FORMATS = {"step", "stl", "iges", "dxf", "pdf"}

# Formats generated by default when a caller doesn't specify. Multi-format
# export is the default as of 2.2.1: every supported format is produced
# unless a caller opts into a narrower list via `formats: [...]`. (Prior
# behavior - STEP+STL only - is still available by passing
# `formats: ["step", "stl"]` explicitly.)
DEFAULT_FORMATS = ("step", "stl", "iges", "dxf", "pdf")

_EXTENSION_BY_FORMAT = {"step": "step", "stl": "stl", "iges": "igs", "dxf": "dxf", "pdf": "pdf"}

ShapeLike = Union[cq.Workplane, cq.Shape, "cq.Assembly"]


def _as_workplane(obj: ShapeLike) -> cq.Workplane:
    """Normalize a Workplane, bare Shape, or Assembly into a Workplane so
    every exporter below has one calling convention. Assemblies are
    flattened to their compound solid - fine for STL/IGES/DXF/PDF, which
    only care about final geometry, not part hierarchy. (STEP export for
    assemblies stays on Assembly.save() elsewhere, since that's what
    preserves named sub-parts in the STEP file - see cad_generator.py.)
    """
    if isinstance(obj, cq.Workplane):
        return obj
    if hasattr(obj, "toCompound"):  # cq.assembly.Assembly
        return cq.Workplane(obj=obj.toCompound())
    return cq.Workplane(obj=obj)  # bare cq.Shape


def validate_formats(formats: list[str]) -> list[str]:
    """Normalize + validate a requested format list. Raises GenerationError
    (400-mapped, see exceptions.py) on anything unrecognized, so a typo'd
    format name fails fast with a clear message instead of silently being
    dropped."""
    normalized = [f.strip().lower() for f in formats if f and f.strip()]
    unknown = sorted(set(normalized) - SUPPORTED_FORMATS)
    if unknown:
        raise UnsupportedFormatError(
            f"Unsupported export format(s): {unknown}. "
            f"Supported formats: {sorted(SUPPORTED_FORMATS)}."
        )
    # de-dupe, preserve first-seen order
    seen: set[str] = set()
    result = []
    for f in normalized:
        if f not in seen:
            seen.add(f)
            result.append(f)
    return result or list(DEFAULT_FORMATS)


# --------------------------------------------------------------------
# STEP / STL - thin wrappers around the exports cad_generator.py already
# did inline, moved here so every format lives behind one interface.
# --------------------------------------------------------------------

def export_step(obj: ShapeLike, path: Path) -> Path:
    cq.exporters.export(_as_workplane(obj), str(path), exportType="STEP")
    return path


def export_stl(obj: ShapeLike, path: Path, tolerance: float = 0.1, angular_tolerance: float = 0.1) -> Path:
    cq.exporters.export(
        _as_workplane(obj),
        str(path),
        exportType="STL",
        tolerance=tolerance,
        angularTolerance=angular_tolerance,
    )
    return path


# --------------------------------------------------------------------
# IGES - exact B-Rep, via OCP's IGESControl_Writer directly.
# --------------------------------------------------------------------

def export_iges(obj: ShapeLike, path: Path) -> Path:
    """Write an exact boundary-representation IGES file. Mirrors the
    standard OCCT STEPControl_Writer pattern cadquery already uses for
    STEP internally, just with IGESControl_Writer, and sets the IGES
    unit flag to millimeters to match every other export in this module
    (cadquery/CQ geometry is unitless-but-conventionally-mm; without
    this the reader on the other end may assume inches)."""
    from OCP.IGESControl import IGESControl_Controller, IGESControl_Writer
    from OCP.Interface import Interface_Static

    workplane = _as_workplane(obj)
    shape = workplane.val()
    occt_shape = shape.wrapped if hasattr(shape, "wrapped") else shape

    IGESControl_Controller.Init_s()
    Interface_Static.SetCVal_s("write.iges.unit", "MM")
    writer = IGESControl_Writer()
    writer.AddShape(occt_shape)
    writer.ComputeModel()

    path.parent.mkdir(parents=True, exist_ok=True)
    ok = writer.Write(str(path))
    if not ok:
        raise GenerationError(f"IGES export failed (OCP IGESControl_Writer.Write returned false) for {path}")
    return path


# --------------------------------------------------------------------
# Multi-view orthographic projection (front / top / side) - the shared
# geometry pipeline behind DXF and PDF export. Built on OCCT's HLRBRep
# hidden-line-removal algorithm via OCP: for a given viewing direction,
# it separates a solid's projected edges into visible (solid line) and
# hidden (dashed line) sets, which is the standard way to turn a 3D part
# into a real technical drawing rather than one flat cross-section.
# --------------------------------------------------------------------

@dataclass
class _View:
    """One projected view's geometry, already expressed in the view's own
    local 2D drawing coordinates (local-X, local-Y - see _VIEW_AXES)."""
    name: str
    label: str
    visible: list[list[tuple[float, float]]]
    hidden: list[list[tuple[float, float]]]
    u_min: float
    u_max: float
    v_min: float
    v_max: float

    @property
    def width(self) -> float:
        return self.u_max - self.u_min

    @property
    def height(self) -> float:
        return self.v_max - self.v_min


# view_name -> (looking_direction, local_horizontal_axis). Local vertical
# is looking_direction x horizontal_axis, so it isn't listed separately.
# Front and top are both defined with local-X = world +X, so a top view
# stacks directly above a front view with no extra horizontal
# registration needed. Front and side are both defined with local-Y =
# world +Z, so a side view sits directly beside a front view with no
# extra vertical registration needed. This is the standard trick that
# makes a 3-view layout line up automatically instead of needing each
# view manually re-aligned - see _layout_three_views.
_VIEW_AXES: dict[str, tuple["cq.Vector", "cq.Vector"]] = {
    "front": (cq.Vector(0, -1, 0), cq.Vector(1, 0, 0)),
    "top": (cq.Vector(0, 0, -1), cq.Vector(1, 0, 0)),
    "side": (cq.Vector(-1, 0, 0), cq.Vector(0, -1, 0)),
}

_VIEW_LABELS = {"front": "FRONT VIEW", "top": "TOP VIEW", "side": "RIGHT SIDE VIEW"}

# Orientation of each view's local axes was worked out algebraically
# against OCCT's HLRAlgo_Projector convention (gp_Ax2(origin, direction,
# x_dir), local-Y = direction x x_dir) rather than checked against a
# rendered drawing, since this sandbox has no network access to install
# cadquery's native OCCT dependencies (see the module docstring and
# tests/test_exporters.py). Visually confirm view orientation the first
# time this runs against real geometry.


def _edge_to_points(edge: "cq.Edge", curve_segments: int = 32) -> list[tuple[float, float]]:
    """Discretize one edge into 2D (x, y) points, dropping z. Valid both
    for the old section-plane use (z is constant, the cut height) and
    for HLR-projected edges (z is projection depth, unneeded once
    visible/hidden classification has already happened)."""
    if edge.geomType() == "LINE":
        pts = [edge.startPoint(), edge.endPoint()]
    else:
        ds = [i / (curve_segments - 1) for i in range(curve_segments)]
        pts = edge.positions(ds)
    return [(p.x, p.y) for p in pts]


def _hlr_edges(shape, direction: "cq.Vector", x_dir: "cq.Vector") -> tuple[list, list]:
    """Run OCCT's HLRBRep_Algo on `shape` for one viewing direction and
    return (visible_edges, hidden_edges) as lists of cq.Edge, in the
    view's local 2D frame - each edge's own X/Y already are the drawing
    coordinates (Z is projection depth)."""
    from OCP.HLRAlgo import HLRAlgo_Projector
    from OCP.HLRBRep import HLRBRep_Algo, HLRBRep_HLRToShape
    from OCP.gp import gp_Ax2, gp_Dir, gp_Pnt

    occt_shape = shape.wrapped if hasattr(shape, "wrapped") else shape

    ax2 = gp_Ax2(
        gp_Pnt(0, 0, 0),
        gp_Dir(direction.x, direction.y, direction.z),
        gp_Dir(x_dir.x, x_dir.y, x_dir.z),
    )
    algo = HLRBRep_Algo()
    algo.Add(occt_shape)
    algo.Projector(HLRAlgo_Projector(ax2))
    algo.Update()
    algo.Hide()

    to_shape = HLRBRep_HLRToShape(algo)

    def _collect(*compounds) -> list:
        out = []
        for comp in compounds:
            if comp is None or comp.IsNull():
                continue
            out.extend(cq.Shape.cast(comp).Edges())
        return out

    # VCompound/HCompound: visible/hidden sharp (C0) edges. Rg1Line*:
    # edges at smooth (tangent, G1) face joins, e.g. a fillet's silhouette
    # - without these a filleted edge's outline goes missing. OutLine*:
    # the true silhouette of a curved surface (e.g. a cylinder's apparent
    # edge), which only exists as an HLR construct, not a real model
    # edge. All three visible sets get one line style; same for hidden.
    visible = _collect(to_shape.VCompound(), to_shape.Rg1LineVCompound(), to_shape.OutLineVCompound())
    hidden = _collect(to_shape.HCompound(), to_shape.Rg1LineHCompound(), to_shape.OutLineHCompound())
    return visible, hidden


def _build_view(shape, name: str) -> _View:
    direction, x_dir = _VIEW_AXES[name]
    visible_edges, hidden_edges = _hlr_edges(shape, direction, x_dir)

    visible_polylines = [_edge_to_points(e) for e in visible_edges]
    hidden_polylines = [_edge_to_points(e) for e in hidden_edges]

    all_pts = [p for line in (visible_polylines + hidden_polylines) for p in line]
    if not all_pts:
        raise GenerationError(
            f"HLR projection produced no edges for the {name} view. "
            "The part may be empty or degenerate."
        )
    xs = [p[0] for p in all_pts]
    ys = [p[1] for p in all_pts]
    return _View(
        name=name,
        label=_VIEW_LABELS[name],
        visible=visible_polylines,
        hidden=hidden_polylines,
        u_min=min(xs),
        u_max=max(xs),
        v_min=min(ys),
        v_max=max(ys),
    )


def _build_three_views(workplane: "cq.Workplane") -> list[_View]:
    shape = workplane.val()
    return [_build_view(shape, name) for name in ("front", "top", "side")]


def _layout_three_views(views: list[_View], gap: float = 15.0) -> dict[str, tuple[float, float]]:
    """Return {view_name: (offset_x, offset_y)} to add to each view's raw
    local coordinates so front/top/side sit in the standard third-angle
    drafting arrangement: top view above the front view (shared X
    registration), right-side view beside the front view (shared Z
    registration), `gap` drawing units (mm) apart."""
    by_name = {v.name: v for v in views}
    front, top, side = by_name["front"], by_name["top"], by_name["side"]

    offsets = {"front": (-front.u_min, -front.v_min)}

    front_top_edge_y = -front.v_min + front.height
    offsets["top"] = (-front.u_min, front_top_edge_y + gap - top.v_min)

    front_right_edge_x = -front.u_min + front.width
    offsets["side"] = (front_right_edge_x + gap - side.u_min, -front.v_min)

    return offsets


def _combined_bbox(
    views: list[_View], offsets: dict[str, tuple[float, float]], label_clearance: float = 6.0
) -> tuple[float, float, float, float]:
    """(min_x, max_x, min_y, max_y) across every view's geometry once
    placed, including room below each view for its label text."""
    xs: list[float] = []
    ys: list[float] = []
    for v in views:
        ox, oy = offsets[v.name]
        xs += [v.u_min + ox, v.u_max + ox]
        ys += [v.v_min + oy - label_clearance, v.v_max + oy]
    return min(xs), max(xs), min(ys), max(ys)


def _build_part_block(obj: "ShapeLike") -> tuple[list[_View], dict[str, tuple[float, float]]]:
    workplane = _as_workplane(obj)
    views = _build_three_views(workplane)
    offsets = _layout_three_views(views)
    return views, offsets


def _stack_part_blocks(
    parts: list[tuple[str, "ShapeLike"]], block_gap: float = 40.0
) -> list[tuple[str, list[_View], dict[str, tuple[float, float]], float]]:
    """Lay out one front/top/side block per part, stacked vertically down
    the page. Each part keeps its own internal `_layout_three_views`
    registration; this only adds a per-block Y shift so blocks don't
    overlap. Returns (part_label, views, offsets, y_shift) tuples - the
    y_shift is added on top of each view's own offset when drawing."""
    blocks: list[tuple[str, list[_View], dict[str, tuple[float, float]], float]] = []
    cursor_y = 0.0
    for name, shape in parts:
        views, offsets = _build_part_block(shape)
        _, _, y_min, y_max = _combined_bbox(views, offsets)
        block_height = y_max - y_min
        y_shift = cursor_y - y_min
        blocks.append((name, views, offsets, y_shift))
        cursor_y += block_height + block_gap
    return blocks


# --------------------------------------------------------------------
# DXF - via ezdxf (full control over layers and line entities; cadquery's
# own DXF exporter doesn't expose per-edge visible/hidden classification).
# --------------------------------------------------------------------

def _dxf_layers(doc) -> None:
    doc.layers.add("VISIBLE", color=7)
    doc.layers.add("HIDDEN", color=8, linetype="DASHED" if "DASHED" in doc.linetypes else "CONTINUOUS")
    doc.layers.add("LABELS", color=7)
    doc.layers.add("BORDER", color=7)


def _draw_view_dxf(msp, view: _View, offset: tuple[float, float]) -> None:
    ox, oy = offset
    for line in view.visible:
        pts = [(x + ox, y + oy) for x, y in line]
        if len(pts) >= 2:
            msp.add_lwpolyline(pts, dxfattribs={"layer": "VISIBLE"})
    for line in view.hidden:
        pts = [(x + ox, y + oy) for x, y in line]
        if len(pts) >= 2:
            msp.add_lwpolyline(pts, dxfattribs={"layer": "HIDDEN"})
    label_x = view.u_min + ox
    label_y = view.v_min + oy - 6
    msp.add_text(view.label, dxfattribs={"layer": "LABELS", "height": 3.0}).set_placement((label_x, label_y))


def _draw_title_block_dxf(
    msp, x0: float, y0: float, width: float, height: float,
    part_name: str, material: str | None, part_type: str | None,
) -> None:
    msp.add_lwpolyline(
        [(x0, y0), (x0 + width, y0), (x0 + width, y0 + height), (x0, y0 + height)],
        dxfattribs={"layer": "BORDER", "closed": True},
    )
    msp.add_line((x0, y0 + height / 2), (x0 + width, y0 + height / 2), dxfattribs={"layer": "BORDER"})
    msp.add_line((x0 + width * 0.5, y0), (x0 + width * 0.5, y0 + height), dxfattribs={"layer": "BORDER"})

    msp.add_text(
        f"PART: {part_name.upper()}", dxfattribs={"layer": "LABELS", "height": 3.5}
    ).set_placement((x0 + 3, y0 + height - 8))
    msp.add_text(
        f"TYPE: {(part_type or 'n/a').upper()}", dxfattribs={"layer": "LABELS", "height": 2.5}
    ).set_placement((x0 + 3, y0 + 3))
    msp.add_text(
        f"MATERIAL: {material or 'n/a'}", dxfattribs={"layer": "LABELS", "height": 2.5}
    ).set_placement((x0 + width * 0.5 + 3, y0 + height - 8))
    msp.add_text(
        f"DATE: {_dt.date.today().isoformat()}", dxfattribs={"layer": "LABELS", "height": 2.5}
    ).set_placement((x0 + width * 0.5 + 3, y0 + 3))


def export_dxf(
    obj: ShapeLike,
    path: Path,
    part_name: str = "PART",
    material: str | None = None,
    part_type: str | None = None,
    parts: list[tuple[str, ShapeLike]] | None = None,
) -> Path:
    """Multi-view orthographic DXF (front/top/side, HLR visible/hidden
    edges, title block). If `parts` is given (assembly sub-parts, see
    assembly.get_assembly_parts), draws one such block per part, stacked
    on one sheet, instead of a single block for `obj`."""
    import ezdxf

    doc = ezdxf.new("R2010")
    _dxf_layers(doc)
    msp = doc.modelspace()

    if parts:
        blocks = _stack_part_blocks(parts)
        for label, views, offsets, y_shift in blocks:
            for view in views:
                ox, oy = offsets[view.name]
                _draw_view_dxf(msp, view, (ox, oy + y_shift))
            first = views[0]
            fx, fy = offsets["front"]
            msp.add_text(
                label.upper(), dxfattribs={"layer": "LABELS", "height": 4.0}
            ).set_placement((fx, fy + y_shift + first.height + 12))
        overall_x0 = overall_y0 = float("inf")
        overall_x1 = overall_y1 = float("-inf")
        for _, views, offsets, y_shift in blocks:
            x0, x1, y0, y1 = _combined_bbox(views, {n: (o[0], o[1] + y_shift) for n, o in offsets.items()})
            overall_x0, overall_x1 = min(overall_x0, x0), max(overall_x1, x1)
            overall_y0, overall_y1 = min(overall_y0, y0), max(overall_y1, y1)
    else:
        views = _build_three_views(_as_workplane(obj))
        offsets = _layout_three_views(views)
        for view in views:
            _draw_view_dxf(msp, view, offsets[view.name])
        overall_x0, overall_x1, overall_y0, overall_y1 = _combined_bbox(views, offsets)

    tb_height = 16.0
    tb_y0 = overall_y0 - tb_height - 10
    _draw_title_block_dxf(
        msp, overall_x0, tb_y0, overall_x1 - overall_x0, tb_height,
        part_name, material, part_type,
    )

    doc.header["$INSUNITS"] = 4  # 4 = millimeters, matches every other export in this module
    path.parent.mkdir(parents=True, exist_ok=True)
    doc.saveas(str(path))
    return path


# --------------------------------------------------------------------
# Vector PDF - same multi-view / multi-part geometry as DXF, via
# reportlab, at true 1:1 scale with a title block.
# --------------------------------------------------------------------

def _draw_open_polyline_pdf(c, points: list[tuple[float, float]], dashed: bool = False) -> None:
    if len(points) < 2:
        return
    c.setDash([2, 2] if dashed else [])
    p = c.beginPath()
    p.moveTo(*points[0])
    for pt in points[1:]:
        p.lineTo(*pt)
    c.drawPath(p, stroke=1, fill=0)
    c.setDash([])


def _draw_view_pdf(c, view: _View, offset: tuple[float, float], to_page) -> None:
    ox, oy = offset
    for line in view.visible:
        pts = [to_page((x + ox, y + oy)) for x, y in line]
        _draw_open_polyline_pdf(c, pts, dashed=False)
    for line in view.hidden:
        pts = [to_page((x + ox, y + oy)) for x, y in line]
        _draw_open_polyline_pdf(c, pts, dashed=True)
    label_pt = to_page((view.u_min + ox, view.v_min + oy - 6))
    c.setFont("Helvetica-Bold", 8)
    c.drawString(label_pt[0], label_pt[1], view.label)


def export_pdf(
    obj: ShapeLike,
    path: Path,
    part_name: str = "PART",
    material: str | None = None,
    part_type: str | None = None,
    parts: list[tuple[str, ShapeLike]] | None = None,
) -> Path:
    """Multi-view orthographic PDF (front/top/side, HLR visible/hidden
    edges, title block), at true 1:1 scale. If `parts` is given (assembly
    sub-parts, see assembly.get_assembly_parts), draws one such block per
    part, stacked on one sheet, instead of a single block for `obj`."""
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas

    if parts:
        blocks = _stack_part_blocks(parts)
        all_offsets = [
            {name: (o[0], o[1] + y_shift) for name, o in offsets.items()}
            for _, _, offsets, y_shift in blocks
        ]
        overall_x0 = overall_y0 = float("inf")
        overall_x1 = overall_y1 = float("-inf")
        for (_, views, _, _), offsets in zip(blocks, all_offsets):
            x0, x1, y0, y1 = _combined_bbox(views, offsets)
            overall_x0, overall_x1 = min(overall_x0, x0), max(overall_x1, x1)
            overall_y0, overall_y1 = min(overall_y0, y0), max(overall_y1, y1)
    else:
        views = _build_three_views(_as_workplane(obj))
        offsets = _layout_three_views(views)
        blocks = [(part_name, views, offsets, 0.0)]
        all_offsets = [offsets]
        overall_x0, overall_x1, overall_y0, overall_y1 = _combined_bbox(views, offsets)

    drawing_w_mm = overall_x1 - overall_x0
    drawing_h_mm = overall_y1 - overall_y0

    margin = 20 * mm
    title_block_h = 28 * mm
    page_w = max(drawing_w_mm * mm + 2 * margin, 150 * mm)
    page_h = drawing_h_mm * mm + 2 * margin + title_block_h

    path.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(path), pagesize=(page_w, page_h))

    origin_x = margin - overall_x0 * mm
    origin_y = margin + title_block_h - overall_y0 * mm

    def to_page(pt: tuple[float, float]) -> tuple[float, float]:
        return (origin_x + pt[0] * mm, origin_y + pt[1] * mm)

    c.setLineWidth(0.5)
    c.setStrokeColorRGB(0, 0, 0)

    for (label, block_views, _, y_shift), offsets in zip(blocks, all_offsets):
        if parts:
            first = block_views[0]
            fx, fy = offsets["front"]
            label_pt = to_page((fx, fy + first.height + 12))
            c.setFont("Helvetica-Bold", 10)
            c.drawString(label_pt[0], label_pt[1], label.upper())
        for view in block_views:
            _draw_view_pdf(c, view, offsets[view.name], to_page)

    # Title block
    tb_x0, tb_y0 = margin, margin
    tb_w = page_w - 2 * margin
    c.rect(tb_x0, tb_y0, tb_w, title_block_h, stroke=1, fill=0)
    c.line(tb_x0, tb_y0 + title_block_h / 2, tb_x0 + tb_w, tb_y0 + title_block_h / 2)
    c.line(tb_x0 + tb_w * 0.38, tb_y0, tb_x0 + tb_w * 0.38, tb_y0 + title_block_h)
    c.line(tb_x0 + tb_w * 0.7, tb_y0, tb_x0 + tb_w * 0.7, tb_y0 + title_block_h)

    c.setFont("Helvetica-Bold", 10)
    c.drawString(tb_x0 + 5, tb_y0 + title_block_h - 14, f"PART: {part_name.upper()}")
    c.setFont("Helvetica", 8)
    c.drawString(tb_x0 + 5, tb_y0 + 8, f"TYPE: {(part_type or 'n/a').upper()}")
    c.drawString(tb_x0 + tb_w * 0.4, tb_y0 + title_block_h - 14, "SCALE: 1:1")
    c.drawString(tb_x0 + tb_w * 0.4, tb_y0 + 8, f"SIZE: {drawing_w_mm:.1f} x {drawing_h_mm:.1f} mm")
    c.drawString(tb_x0 + tb_w * 0.72, tb_y0 + title_block_h - 14, f"MATERIAL: {material or 'n/a'}")
    c.drawString(tb_x0 + tb_w * 0.72, tb_y0 + 8, f"DATE: {_dt.date.today().isoformat()}")

    c.showPage()
    c.save()
    return path


# --------------------------------------------------------------------
# Orchestrator
# --------------------------------------------------------------------

def export_all(
    obj: ShapeLike,
    output_dir: Path,
    base_name: str,
    formats: list[str] | None = None,
    part_name: str | None = None,
    material: str | None = None,
    part_type: str | None = None,
    parts: list[tuple[str, ShapeLike]] | None = None,
) -> dict[str, Path]:
    """Export `obj` to every format in `formats` (default: every format in
    DEFAULT_FORMATS - step, stl, iges, dxf, pdf). Returns
    {format: output_path}. Raises GenerationError on an unknown format or
    if any individual export fails - callers that want partial success on
    partial failure should call the individual export_* functions
    directly instead.

    `parts`: optional list of (name, shape) for assembly sub-parts (see
    assembly.get_assembly_parts). Only affects dxf/pdf, which draw one
    multi-view block per part instead of one block for `obj`. step/stl/
    iges are unaffected and still export `obj` as-is - STEP already
    preserves named sub-parts via Assembly.save() (see cad_generator.py),
    and STL/IGES don't have a per-part drawing concept.
    """
    resolved_formats = validate_formats(list(formats) if formats else list(DEFAULT_FORMATS))
    label = part_name or base_name

    results: dict[str, Path] = {}
    for fmt in resolved_formats:
        out_path = output_dir / f"{base_name}.{_EXTENSION_BY_FORMAT[fmt]}"
        try:
            if fmt == "step":
                export_step(obj, out_path)
            elif fmt == "stl":
                export_stl(obj, out_path)
            elif fmt == "iges":
                export_iges(obj, out_path)
            elif fmt == "dxf":
                export_dxf(obj, out_path, part_name=label, material=material, part_type=part_type, parts=parts)
            elif fmt == "pdf":
                export_pdf(obj, out_path, part_name=label, material=material, part_type=part_type, parts=parts)
        except GenerationError:
            raise
        except Exception as exc:  # noqa: BLE001 - cadquery/OCP/ezdxf/reportlab all raise different types
            raise GenerationError(f"{fmt.upper()} export failed: {exc}") from exc
        results[fmt] = out_path

    return results
